---
name: CI

# https://github.com/actions/checkout
# https://github.com/ruby/setup-ruby
# https://github.com/actions/virtual-environments#available-environments
# https://github.com/ruby/setup-ruby/blob/master/README.md#supported-platforms

'on': [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: >-
      test ${{ matrix.os }} ${{ matrix.ruby }}

    runs-on: ubuntu-latest-ppc64le
    if: |
      !(   contains(github.event.pull_request.title,  '[ci skip]')
        || contains(github.event.pull_request.title,  '[skip ci]'))
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.3.0'

    steps:
      - name: repo checkout
        uses: actions/checkout@v4

      - name: load ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none

      - name: install hoe
        run: gem install hoe -N

      - name: rake test
        run: |
          rake test
        timeout-minutes: 3
